import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { getServerAuthSession } from "~/server/auth";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,dashboard,signIn
}: {
  children: React.ReactNode;
  dashboard: React.ReactNode;
  signIn: React.ReactNode;
}) {

  const session = await getServerAuthSession()
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider headers={headers()}>
          {!session?signIn:dashboard}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
